[package]
name = "aws-lambda-starter-rs"
version = "0.1.0"
authors = ["Your Name <your.name@email.com>"]
edition = "2018"

[dependencies]
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
lambda_runtime = "0.2.1"
lambda_http = "0.1.0"
lazy_static = "1.3.0"
regex = "1.2.0"
reqwest = "0.9.19"

[[bin]]
name = "bootstrap"
path = "src/main_lambda.rs"

[[bin]]
name = "local"
path = "src/main.rs"

#[profile.release]
#opt-level = 'z'
#lto = true
#codegen-units = 1
#panic = 'abort'
